version: '3'
services:
  data-accessor-mysql-web:
    image: toposoid/toposoid-rdb:0.6-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=data-accessor-mysql-web
      - TOPOSOID_RDB_HOST=mysql
      - PLAY_HTTP_PORT=9016
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.37
    environment:
      - MYSQL_DATABASE=toposoiddb
      - MYSQL_USER=toposoid
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
      - TZ=UTC
    volumes:
      - ./conf/evolutions/default:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

